# datasets = ["ArticularyWordRecognition","BasicMotions","Cricket",
#             "DuckDuckGeese","EigenWorms", "Epilepsy","ERing","EthanolConcentration","FaceDetection","FingerMovements",
#             "HandMovementDirection","Handwriting","Heartbeat",
#             "Libras","LSST","MotorImagery","NATOPS","PEMS-SF","PenDigits","PhonemeSpectra",
#             "RacketSports", "SelfRegulationSCP1","SelfRegulationSCP2",
#             "StandWalkJump","UWaveGestureLibrary"]
datasets = ['ArrowHead', 
            'BeetleFly', 
            'Ham', 
            'MoteStrain', 
            'OliveOil', 
            'Wine', 
            'Lightning7', 
            'InlineSkate', 
            'Beef', 
            'ACSF1', 
            'Yoga', 
            'GunPointOldVersusYoung',
            'FreezerSmallTrain', 
            'WordSynonyms', 
            'Car', 
            'ProximalPhalanxTW', 
            'InsectWingbeatSound',
            'FaceAll', 
            'EOGVerticalSignal',  
            'Earthquakes']