version: '3'
services:
  my_service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./main.py:/app/main.py
      - ./requirements.txt:/app/requirements.txt
    # environment:
    #   - PYTHONUNBUFFERED=1
